# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    cleaner.yml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rtrant <rtrant@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/10/06 13:25:29 by rtrant            #+#    #+#              #
#    Updated: 2020/10/06 14:05:09 by rtrant           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: cleaner

on: push

jobs:
  cleaner:
    name: Clean workspace
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/clean-action
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}